version: '3.9'
services:
  app:
    build: .
    container_name: ktor_app
    ports:
      - "8080:8080"
    environment:
      # In docker network service names become hostnames, so we should use 'db' as the host
      DATABASE_HOST: db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    # Make sure the app waits for the database to be ready, although the app will fail on connection
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: ktor_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -h localhost -p 5432" ]
      interval: 2s
      timeout: 2s
      retries: 10
