ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

database:
  driver: org.postgresql.Driver
  host: {DATABASE_HOST}
  user: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  name: ${DATABASE_NAME}